apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetport: {{ .Values.port }}
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.serviceType }}