name: Reusable - Deploy AWS Lambda

on:
  workflow_call:
    inputs:
      func_name:
        required: true
        type: string
      lambda_uri:
        required: true
        type: string
    secrets:
      aws_access_key:
        required: true
      aws_secret_key:
        required: true

jobs:
  deploy_lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Get URI of the Docker image from previous job
        run: echo "The URI of the Docker image is ${{ needs.build-docker-ecr.outputs.image_uri }}"
      
      - name: Deploy container lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.aws_access_key }}
          aws_secret_access_key: ${{ secrets.aws_secret_key }}
          aws_region: us-east-1
          function_name: ${{ inputs.func_name }}
          image_uri: ${{ inputs.lambda_uri }}