name: Main CI/CD

on:
  workflow_dispatch:

jobs:
  scan-code:
    name: Scan code with CodeQL
    uses: gakovski/dotnet-todo/.github/workflows/scan-code.yaml@main
    permissions:
      security-events: write
      actions: read
      contents: read

  build-docker:
    name: Build Docker Container
    needs: scan-code
    uses: gakovski/dotnet-todo/.github/workflows/build.yaml@main
    with:
      image_name: 'to-do-api'
      image_tag: 'latest'
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-cluster:
    name: Deploy K8S Cluster
    uses: gakovski/dotnet-todo/.github/workflows/deploy.yaml@main
    strategy:
      matrix:
        env: [train, prod]
    with:
      environment: '${{ matrix.env }}'

  #create-release:
  #  uses: gakovski/dotnet-todo/.github/workflows/release.yaml@main
  #  secrets:
  #    github_token: ${{ secrets.GITHUB_TOKEN }}
