name: Main CI/CD
run-name: Workflow started for ${{ github.actor }}. Run number ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: Deploy Cluster to Production
        required: true
        type: boolean

jobs:
  scan-code:
    name: Scan code with CodeQL
    uses: gakovski/dotnet-todo/.github/workflows/scan-code.yaml@main
    permissions:
      security-events: write
      actions: read
      contents: read

  build-docker:
    name: Build Docker Container
    needs: scan-code
    uses: gakovski/dotnet-todo/.github/workflows/build.yaml@main
    with:
      image_name: 'to-do-api'
      image_tag: 'latest'
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-cluster-train:
    name: Deploy K8S Cluster - Train
    needs: build-docker
    uses: gakovski/dotnet-todo/.github/workflows/deploy.yaml@main
    with:
      environment: 'train'

  deploy-cluster-prod:
    name: Deploy K8S Cluster - Prod
    needs: deploy-cluster-train
    if: ${{ inputs.deploy_prod }}
    uses: gakovski/dotnet-todo/.github/workflows/deploy.yaml@main
    with:
      environment: 'prod'

  create-release:
    name: Create Release Notes
    needs: deploy-cluster-prod
    uses: gakovski/dotnet-todo/.github/workflows/release.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
